from .enums import ConfidenceLevel, DivergenceType, ReviewStatus
from .models import (
    Cluster,
    ComparisonRun,
    DivergenceAssessment,
    DivergenceFinding,
    DivergenceObservation,
    JurisdictionScope,
    LegalScope,
    LegalScopeReviewCandidate,
    NarrativeExport,
    Proposition,
    PropositionCompletenessAssessment,
    PropositionDatasetComparisonRun,
    PropositionDatasetMetadata,
    PropositionExtractionTrace,
    PropositionScopeLink,
    RegistryAnalysisScope,
    ReviewDecision,
    RunArtifact,
    RunStageTrace,
    SourceCategorisationRationale,
    SourceDocument,
    SourceFetchAttempt,
    SourceFetchMetadata,
    SourceFragment,
    SourceParseTrace,
    SourceInventoryArtifact,
    SourceInventoryRow,
    SourceRecord,
    SourceSnapshot,
    SourceTargetLink,
    Topic,
)
from .pipeline_review import PipelineReviewDecision
from .run_comparison import RunComparisonChangeGroup, RunComparisonSummary
from .run_quality import RunQualityGateResult, RunQualitySummary
from .source_family import (
    SourceFamilyCandidate,
    SourceFamilyConfidence,
    SourceFamilyInclusionStatus,
    SourceFamilyRelationship,
    SourceFamilySourceRole,
)

# Deprecated migration shim: canonical type name is SourceRecord.
# Keep SourceDocument export temporarily for downstream imports that have not migrated yet.

__all__ = [
    "PipelineReviewDecision",
    "RunComparisonChangeGroup",
    "RunComparisonSummary",
    "RunQualityGateResult",
    "RunQualitySummary",
    "Cluster",
    "ComparisonRun",
    "ConfidenceLevel",
    "JurisdictionScope",
    "RegistryAnalysisScope",
    "PropositionDatasetComparisonRun",
    "PropositionDatasetMetadata",
    "DivergenceAssessment",
    "DivergenceFinding",
    "DivergenceObservation",
    "DivergenceType",
    "LegalScope",
    "LegalScopeReviewCandidate",
    "NarrativeExport",
    "Proposition",
    "PropositionCompletenessAssessment",
    "PropositionExtractionTrace",
    "PropositionScopeLink",
    "ReviewDecision",
    "ReviewStatus",
    "RunArtifact",
    "RunStageTrace",
    "SourceCategorisationRationale",
    "SourceDocument",
    "SourceFetchAttempt",
    "SourceFamilyCandidate",
    "SourceFamilyConfidence",
    "SourceFamilyInclusionStatus",
    "SourceFamilyRelationship",
    "SourceFamilySourceRole",
    "SourceFetchMetadata",
    "SourceFragment",
    "SourceParseTrace",
    "SourceInventoryArtifact",
    "SourceInventoryRow",
    "SourceRecord",
    "SourceSnapshot",
    "SourceTargetLink",
    "Topic",
]
